
class BaseException(Exception):
    def __init__(self):
        pass

class PhoneNotFoundError(BaseException):
    def __init__(self):
        pass
